### ISSUE TITLE
Skydome interacting with alpha rendering

### ISSUE THREAD

**Issue by jcandres** [jk7c/jc.godot3.time-of-day#3]
I noticed that the skydome causes rendering issues. It seems that it pokes through any pixel that's not entirely opaque.

This is the example scene with a cube added. The material is the default SpatialMaterial with transparency enabled. The skydome renders incorrectly on top, but seems that only the lower gradient has this problem.
In fact I noticed that if you disable `sky_visible` in the `TOD_Skydome`, this gradient remains visible.

![imagen](https://user-images.githubusercontent.com/7023706/177123727-59c5f859-ef40-4c13-b10a-583f54c645c6.png)

Thanks.

**Comment by Jay7c** [comment]
> I noticed that the skydome causes rendering issues. It seems that it pokes through any pixel that's not entirely opaque.
> 
> This is the example scene with a cube added. The material is the default SpatialMaterial with transparency enabled. The skydome renders incorrectly on top, but seems that only the lower gradient has this problem. In fact I noticed that if you disable `sky_visible` in the `TOD_Skydome`, this gradient remains visible.
> 
> ![imagen](https://user-images.githubusercontent.com/7023706/177123727-59c5f859-ef40-4c13-b10a-583f54c645c6.png)
> 
> Thanks.

This is caused by fog. I will try to find a solution for transparent objects in future versions.

**Comment by Jay7c** [comment]
> I noticed that the skydome causes rendering issues. It seems that it pokes through any pixel that's not entirely opaque.
> 
> This is the example scene with a cube added. The material is the default SpatialMaterial with transparency enabled. The skydome renders incorrectly on top, but seems that only the lower gradient has this problem. In fact I noticed that if you disable `sky_visible` in the `TOD_Skydome`, this gradient remains visible.
> 
> ![imagen](https://user-images.githubusercontent.com/7023706/177123727-59c5f859-ef40-4c13-b10a-583f54c645c6.png)
> 
> Thanks.

For now set the Depth Draw Mode -> Opaque-Prepass in your transparent material.

**Comment by jcandres** [comment]
I see, thanks for looking at this.

**Comment by Jay7c** [comment]
> I see, thanks for looking at this. Is there a way to enable the default Environment fog meanwhile?

A temporary solution:

I add a gradient for the default fog in the master branch, you can combine the two effects. Be sure the "render priority" property of the atmospheric fog is lower than that of your transparent objects.
![fo](https://user-images.githubusercontent.com/75779389/177905578-6cccc506-3e0c-4904-a40a-85dc3d2f1271.png)

**Comment by Jay7c** [comment]
All the solutions that I found for the 3x version(without modifying the source code) are not very intuitive for the user. It also implies that they only work for one camera. For now it is better to combine both effects. In godot 4 this will not be a problem.
