### ISSUE TITLE
Doesn't work on Godot 3.4.4 and  3.5

### ISSUE THREAD

**Issue by br3eze** [jk7c/jc.godot3.time-of-day#4]
Versions 3.4.4 and 3.5:

"Unable to load addon script from path: 'res://addons/jc.godot3.time-of-day-1.1/scr/time_of_day_plugin.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/jc.godot3.time-of-day-1.1/plugin.cfg' to prevent further errors."

**Comment by Jay7c** [comment]
> Versions 3.4.4 and 3.5:
> 
> "Unable to load addon script from path: 'res://addons/jc.godot3.time-of-day-1.1/scr/time_of_day_plugin.gd'. This might be due to a code error in that script. Disabling the addon at 'res://addons/jc.godot3.time-of-day-1.1/plugin.cfg' to prevent further errors."

Can you show a screenshot of the folder where you have the plugin?

**Comment by Jay7c** [comment]
> Versions 3.4.4 and 3.5:
> 
> "Unable to load addon script from path: 'res://addons/jc.godot3.time-of-day-1.1/scr/time_of_day_plugin.gd'. This might be due to a code error in that script. Disabling the addon at 'res://addons/jc.godot3.time-of-day-1.1/plugin.cfg' to prevent further errors."

The folder name is wrong, replace the folder name `jc.godot3.time-of-day-1.1` with `jc.godot3.time-of-day`

**Comment by br3eze** [comment]
This fix it, but..

![Screenshot_20220722_142612](https://user-images.githubusercontent.com/5236855/180388052-6d3da495-9d4c-463b-bc2f-e2f2aea44c75.png)
![Screenshot_20220722_143212](https://user-images.githubusercontent.com/5236855/180388074-192f5976-57b8-4810-afef-2545de58c69f.png)
![Screenshot_20220722_142829](https://user-images.githubusercontent.com/5236855/180388062-2d0652af-2f3e-4d3e-a7cf-c17f2f2f0f5b.png)

The bug in the 3.4.4 at least with a new default project. Can't use 3.5 - it still has some bugs while it not released.

**Comment by br3eze** [comment]
I've missed this part:

![image](https://user-images.githubusercontent.com/5236855/180390043-53810f0f-acf4-40a8-a2ae-d34050b92bee.png)

**Comment by Jay7c** [comment]
> I've missed this part:
> 
> ![image](https://user-images.githubusercontent.com/5236855/180390043-53810f0f-acf4-40a8-a2ae-d34050b92bee.png)

For godot 3.4 remove the `async_visible ` keyword  in the render mode of all shaders.
