### ISSUE TITLE
Failed to Load in Godot

### ISSUE THREAD

**Issue by Jillinger** [jk7c/jc.godot3.time-of-day#6]
Is this plugin incompatible with Godot 3.5?
I'm getting a error:

> Unable to load addon script from path: 'res://addons/time-of-day/scr/time_of_day_plugin.gd'. This might be due to a code error in that script.
> Disabling the addon at 'res://addons/time-of-day/plugin.cfg' to prevent further errors.

**Comment by jk7c** [comment]
> Is this plugin incompatible with Godot 3.5? I'm getting a error:
> 
> > Unable to load addon script from path: 'res://addons/time-of-day/scr/time_of_day_plugin.gd'. This might be due to a code error in that script.
> > Disabling the addon at 'res://addons/time-of-day/plugin.cfg' to prevent further errors.

You need to restart the editor after installing.

**Comment by Jillinger** [comment]
> You need to restart the editor after installing.

I have restarted the editor several times, and got the same error.

**Comment by jk7c** [comment]
> > You need to restart the editor after installing.
> 
> I have restarted the editor several times, and got the same error.

In the plugin.cfg file try replacing this line:

`script="/scr/time_of_day_plugin.gd"`

With this:

`script="scr/time_of_day_plugin.gd"`

Then restart the editor.

**Comment by roza237** [comment]
What worked for me is to make sure the folder is named "_jc.godot3.time-of-day_" within the _addons_ directory.

This is because in the script _/scr/time_of_day_plugin.gd_ you'll notice that the path to the various preloaded resources are hard-coded with a specific directory path.

**Comment by jk7c** [comment]
I'm deprecating the version for godot 3x. Godot 3x does not support real-time PBR reflections(radiance cubemap) for sky, current hack (SkyProbe) is very slow. If he uses a reflection probe you will have to sacrifice the others and the GI Probe, there are also artifacts.

I will focus on the version for godot 4, At the moment I will close this issue, the version of godot 4 will be uploaded to the asset library, so it should be easy to install it without problems.
